announcement/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index,  name='index'),
    path('addcomment/<int:id>', views.addcomment, name='addcomment')

    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index,  name='index')
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('user/', include('user.urls')),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('references/', views.references, name='references'),
    path('contactus/', views.contactus, name='contactus'),
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('announcement/', include('announcement.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_products, name ='category_products'),
    path('announcement/<int:id>/<slug:slug>/', views.announcement_detail, name='announcement_detail'),
    path('search/', views.announcement_search, name='announcement_search'),
    path('search_auto/', views.announcement_search_auto, name='announcement_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('join/', views.join_view, name='join_view'),
    path('faq/', views.faq, name='faq'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('menu/<int:id>/<slug:slug>', views.content_detail, name='content_detail'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #path('comments/', views.comments, name='comments'),
    # path('contents/', views.contents, name='contents'),
    # path('contentedit/<int:id>', views.contentedit, name='contentedit'),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

announcement/models.py
from ckeditor.widgets import CKEditorWidget
from django.contrib.auth.models import User
from django.db import models
#from ckeditor.widgets import CKEditorWidget
# Create your models here.
from django.forms import ModelForm, Select, TextInput, FileInput
from django.urls import reverse
from django.utils.safestring import mark_safe
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class Category (MPTTModel):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )

    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    status = models.CharField(max_length=10, choices=STATUS)
    slug = models.SlugField(null=False, unique=True)
    parent = TreeForeignKey('self', blank=True, null=True, related_name='children', on_delete=models.CASCADE)
    # create_at = models.DataTimeField(auto_now_add=True)
    # update_at = models.DataTimeFiled(auto_now_add=True)



    class MPTTMeta:

        order_insertion_by = ['title']


    def __str__(self):
        full_path = [self.title]
        k = self.parent
        while k is not None:
            full_path.append(k.title)
            k = k.parent
        return ' -> '.join(full_path[::-1])


    def image_tag(self):
        return mark_safe('<img src="{}" height ="50/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Announcement(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.ImageField(blank=True, upload_to='images/')
    detail = models.CharField(max_length=255)
    slug = models.SlugField(null=False, unique=True)
    status = models.CharField(max_length=10, choices=STATUS)
    # create_at = models.DataTimeField(auto_now_add=True)
    # update_at = models.DataTimeFiled(auto_now_add=True)

    def __str__(self):
        return self.title

    def image_tag(self):
        return mark_safe('<img src="{}" height ="50/>'.format(self.image.url))

    image_tag.short_description = 'Image'

    def get_absolute_url(self):
        return reverse('announcement_detail', kwargs={'slug': self.slug})




class AnnouncementForm(ModelForm):
    class Meta:
        model = Announcement
        fields = ['category', 'title', 'slug', 'image', 'keywords', 'description', 'detail']
        widgets = {
            'category': Select(attrs={'class': 'input', 'placeholder': 'type'}, choices=Category.objects.all()),
            'title': TextInput(attrs={'class': 'input', 'placeholder': 'title'}),
            'slug': TextInput(attrs={'class': 'input', 'placeholder': 'slug '}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
            'keywords': TextInput(attrs={'class': 'input', 'placeholder': 'keywords'}),
            'description': TextInput(attrs={'class': 'input', 'placeholder': 'description'}),
            'detail':  CKEditorWidget(),
        }


class Comment(models.Model):
    STATUS = (
        ('New', 'Yeni'),
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )

    announcement = models.ForeignKey(Announcement, on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    subject = models.CharField(max_length=50, blank = True)
    comment = models.TextField(max_length=200,blank = True)
    rate = models.IntegerField()
    status = models.CharField(max_length=10, choices=STATUS,default="New")
    ip = models.CharField(blank=True, max_length=20)
    # create_at = models.DataTimeField(auto_now_add=True)
    # update_at = models.DataTimeFiled(auto_now_add=True)




    def __str__(self):
        return self.subject


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['subject','comment','rate']

class Images (models.Model):
    announcement = models.ForeignKey(Announcement,on_delete=models.CASCADE)
    title=models.CharField(max_length=50,blank=True)
    image=models.ImageField(blank=True,upload_to='images/')
    def __str__(self):
        return self.title
    def image_tag(self):
        return mark_safe('<img src="{}" height"50"/>)'.format(self.image.url))
    image_tag.short_description='Image'


class AnnouncementImageForm(ModelForm):
    class Meta:
        model = Images
        fields = ['title','image']

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import  ModelForm,TextInput, Textarea
from django.utils.safestring import mark_safe


class Settings(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    school = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True,max_length=15)
    fax = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=255)
    smtserver =models.CharField(blank=True,max_length=20)
    smtemail =models.CharField(blank=True,max_length=20)
    smtpassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True,max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook =models.CharField(blank=True,max_length=50)
    instagram =models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references =  RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    # create_at = models.DataTimeField(auto_now_add=True)
    # update_at = models.DataTimeFiled(auto_now_add=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),

    )
    name = models.CharField(blank = True, max_length=20)
    email= models.CharField(blank = True,max_length=50)
    subject = models.CharField(blank = True,max_length=50)
    message = models.CharField(blank = True,max_length=255)
    status = models.CharField (max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank = True,max_length=20)
    note = models.CharField(blank = True,max_length=100)
    # create_at = models.DataTimeField(auto_now_add=True)
    # update_at = models.DataTimeFiled(auto_now_add=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
             'name': TextInput(attrs={'class' : 'input', 'placeholder' : 'Name & Surname'}),
             'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
             'email' : TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
             'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows':'5'}),
        }




class UserProfile(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.CharField(blank =True,max_length=20)
    adress = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image =models.ImageField(blank=True, upload_to='images/users/')


    def __str__(self):
        return self.user.username

    def user_name(self):
        return  self.user.first_name + ' ' + self.user.last_name + ' ' + '[' + self.user.username + ']'

    def image_tag(self):
        return mark_safe('<img src="{}" height ="50/>'.format(self.image.url))

    image_tag.short_description = 'Image'



class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'adress', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )
    ordernumber =models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField(max_length=255)
    status = models.CharField(max_length=10, choices=STATUS)
    #created_at
    #updated_at

    def __str__(self):
        return self.question

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length = 100)
    catid = forms.IntegerField()



class JoinForm(UserCreationForm):
    username = forms.CharField(max_length=30, label='User Name :')
    email = forms.EmailField(max_length=200,label='Email :')
    first_name = forms.CharField(max_length=100, help_text='First Name', label='First Name :')
    last_name = forms.CharField(max_length=100, help_text='Last Name', label='Last Name :')

    class Meta:
        model = User
        fields =('username','email','first_name', 'last_name','password1','password2')

announcement/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from announcement.models import CommentForm, Comment


def index(request):
    return HttpResponse("Announcement Page")





@login_required(login_url='/login')
def addcomment(request,id):
    url =request.META.get('HTTP_REFERER')

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            current_user = request.user
            data = Comment()
            data.user_id =current_user.id
            data.announcement_id = id
            data.subject= form.cleaned_data['subject']
            data.comment = form.cleaned_data['comment']
            data.rate = form.cleaned_data['rate']
            data.ip =request.META.get('REMOTE_ADDR')
            data.save()
            messages.success(request, "yorum alındı. teşekkürler")
            url = request.META.get('HTTP_REFERER')

            return HttpResponseRedirect(url)

    messages.error(request,"yorum kaydedilmei")
    return HttpResponseRedirect(url)

home/templates/aboutus.html
{% extends "homebase.html" %}

{% block  title %} Aboutus---{{ setting.school }}  {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %} {{ setting.description }} {% endblock %}

{% block body %}
<link rel ='shortcut icon' type="image/icon" href = '{{setting.icon.url}}' />
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}


{% block  content %}
 <div class="content">
     <div class="content_resize">
    <div class="mainbar">
          {{ setting.aboutus|safe }}
          </div>

            {% include 'sidebar.html' %}
          <div class="clr"></div>
    </div>
  </div>

{% endblock %}

home/templates/announcement.html
{% extends "homebase.html" %}

{% block  title %}  {{ categorydata.title}}  {% endblock %}
{% block  keywords %} {{ categorydata.keywords }} {% endblock %}
{% block  description %} {{ categorydata.description }} {% endblock %}

{% block head %}
<link rel ='shortcut icon' type="image/icon" href = '{{setting.icon.url}}' />
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}

{% block  body %}




 <div class="content">
            <div class="content_resize">

                 <div class="mainbar">

                     <div class="clr"></div>

                       <div class="article">

                      <h2> {{ categorydata.title}} </h2>
                            {% for rs in announcement %}
                      <div class="clr"></div>
                      <div class="comment">
                          <a href="/announcement/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }}
                              <img src="{{ rs.image.url }}" width="300" height="200" alt="" class="userpic" />
                          </a>

                        <p>{{ rs.description }}</p>
                      </div>
                           {% endfor %}


                    </div>





                </div>



<!--                  {% include 'sidebar.html' %}-->

                  <div class="clr"></div>
        </div>-->




 </div>


{% endblock %}

home/templates/announcement_detail.html
{% extends "homebase.html" %}

{% block  title %} {{ announcement.school }}  {% endblock %}
{% block  keywords %} {{ announcement.keywords }} {% endblock %}
{% block  description %} {{ announcement.description }} {% endblock %}

{% block body %}
<link rel='shortcut icon' type="image/icon" href='{{setting.icon.url}}'/>
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}


{% block  content %}
<div class="content">
    <div class="content_resize">
        <div class="mainbar">
            <div class="article">
                <div class="comment">
                    <h2><span>{{ announcement.title }}</span></h2>
                    <!--                    <a>
                                            <img src="{{ announcement.image.url }}" width="300" height="200" alt="" class="userpic"/>
                                        </a>-->
                    <div class="row">
                        <div id="carouselExampleIndicators" class="carousel slide col-3" data-ride="carousel" >
                            <ol class="carousel-indicators" >
                                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                                <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
                            </ol>
                            <div class="carousel-inner" >
                                <div class="carousel-item active">
                                    <img src="{{ announcement.image.url }}" width="300" height="200" alt=""
                                         class="userpic"/>
                                </div>
                                {% for rs in images %}
                                <div class="carousel-item">
                                    <img src="{{ rs.image.url }}" width="300" height="200" alt="" class="userpic"/>
                                </div>
                                {% endfor %}

                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                               data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                               data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                        <div div class="col-9">
                            <p> {{ announcement.description }} </p>
                            <p>{{ announcement.detail }} </p>
                        </div>
                    </div>
                </div>


            </div>
            <div class="clr"></div>
            <div class="clr"></div>

            <div class="article">

                {%if comments %}
                <h2> Hakkında Yapılan Yorumlar</h2>
                <div class="clr"></div>
                {% for comment in comments %}
                 <p> {{ comment.user.first_name }}</p>
                <div class="comment"><a href="#">{{ comment.subject }}</a>

                    <p>{{ comment.comment }}</p>
                    <p>{{ comment.rate }}</p>

                </div>

                {% endfor %}
                {% else %}
                <h2><span>0</span> / Hakkında  Yorum Bulunmamaktadır</h2>
                {% endif %}
            </div>
            <div class="clr"></div>

            <div class="article">
                <h2><span>Leave a</span> Reply</h2>
                <form action="/announcement/addcomment/{{ announcement.id }}" method="post">
                    {% csrf_token %}
                    <ol>
                        <li>
                            <label for="id_subject"> Subject (required)</label>
                            <input class="input form-control" type="text" id="id_subject" name="subject"
                                   placeholder="Subject"/>
                        </li>

                        <li>
                            <label for="exampleFormControlSelect1"> Rate (required)</label>

                            <select class="form-control" id="exampleFormControlSelect1">
                                <option value="1" id="value1" name="rate">1</option>
                                <option value="2" id="value2" name="rate">2</option>
                                <option value="3" id="value3"name="rate">3</option>
                                <option value="4" id="value4"name="rate">4</option>
                                <option value="5" id="value5" name="rate">5</option>
                            </select>

                        </li>
                        <li>
                            <label for="id_comment">Your Message</label>
                            <textarea class="input form-control" id="id_comment" name="comment"
                                      placeholder="Your review"></textarea>
                        </li>
                        <li>
                            {% if user.id is not None %}
                            <button class="primary-btn">Send Comment</button>
                            {% else %}
                            You must LogIn!
                            {% endif %}
                        </li>
                    </ol>
                </form>
            </div>
            <!-- <div class="article">
                     <h2><span>Leave a</span> Reply</h2>
                     <div class="clr"></div>
                     {%if messages %}
                     {% for message in messages %}
                     <div class="alert-alert- {{ message.tags }}" role="alert">
                         {{ message }}
                         {% endfor %}
                         {% endif %}
                         <p>your mail nor definited</p>
                     </div>
                     <form action="/announcement/addcomment/{{ announcement.id }}" method="post">
                         {% csrf_token %}
                         <div>

                             <input class="input" type="text" id="id_subject" name="subject" placeholder="Subject"/>
                         </div>
                         <div>
                                 <textarea class="input" id="id_comment" name="comment"
                                           placeholder="Your review"></textarea>
                         </div>
                         <div>
                             <div>
                                 <strong>Your Rating</strong>
                                 <div class="stars">
                                     <input type="radio" id="star5" name="rate" value="5"/><label
                                         for="star5"></label>
                                     <input type="radio" id="star4" name="rate" value="5"/><label
                                         for="star4"></label>
                                     <input type="radio" id="star3" name="rate" value="5"/><label
                                         for="star3"></label>
                                     <input type="radio" id="star2" name="rate" value="5"/><label
                                         for="star2"></label>
                                     <input type="radio" id="star1" name="rate" value="5"/><label
                                         for="star1"></label>

                                 </div>
                             </div>
                         </div>
                         {% if user.id is not None %}
                         <button class="primary-btn">Send Comment</button>
                         {% else %}
                         You must LogIn!
                         {% endif %}

                     </form>


                 </div>-->
            <!--            <div class="article">
                <h2><span>{{ announcement.title }} </span></h2>

                <div class="clr"></div>

                <div class="sb_menu">
&lt;!&ndash;                    <li><a href="/category/{{ announcement.category_id }}/{{ announcement.category.slug }}">&ndash;&gt;
&lt;!&ndash;                        <strong>{{ announcement.category }} </strong></a></li>&ndash;&gt;
&lt;!&ndash;                    <li><a href="#"><strong>Lorem ipsum</strong></a></li>&ndash;&gt;

                    <div class="comment"><a href="#"><img src="{{ announcement.image.url }}" width="200" height="200"
                                                          alt="" class="userpic"/></a>
                    </div>



                </div>



            </div>-->

        </div>

        <div class="clr"></div>
    </div>
</div>

{% endblock %}

home/templates/announcement_search.html
{% extends "homebase.html" %}

{% block  title %} Product Search Result  {% endblock %}
{% block  keywords %} {{ categorydata.keywords }} {% endblock %}
{% block  description %} {{ categorydata.description }} {% endblock %}

{% block body %}
<link rel ='shortcut icon' type="image/icon" href = '{{setting.icon.url}}' />
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}


{% block  content %}
 <div class="content">
     <div class="content_resize">
    <div class="mainbar">
        <li class="active">{{ categorydata.title }}</li>


        <table cellpadding="3" width="80">
            <tr>
                <th>Image</th>
                <th>Announcement Name</th>
                 <th>Category</th>

            </tr>

            {% for rs in announcement %}
                <tr>
                    <td> <a href="/announcement/{{ rs.id }}/{{ rs.slug }}"><img src =" {{ rs.image.url }} " height="70" weight="70"></a></td>
                    <td> <h4 class= "announcement_name"><a href="/announcement/{{ rs.id }}/{{ rs.slug }}">{{ rs.title }} </a></h4></td>
                    <td> <a href="/category/{{ rs.category.id }}/{{ rs.category.slug }}"><h4>{{ rs.category }} </h4></a></td>

                </tr>
            {% endfor %}
        </table>
          </div>

            {% include 'sidebar.html' %}
          <div class="clr"></div>
    </div>
  </div>

{% endblock %}

home/templates/contactus.html
{% extends "homebase.html" %}

{% block  title %} Contactus--- {{ setting.school }}  {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel ='shortcut icon' type="image/icon" href = '{{setting.icon.url}}' />
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}

{% block  body %}




<div class="content">
    <div class="content_resize">
        <div class="mainbar">
           {{ setting.contact|safe }}
        </div>
          {% include 'sidebar.html' %}
          <div class="clr"></div>
    </div>
  </div>-->

{% endblock %}

home/templates/content_detail.html
{% extends "homebase.html" %}

{% block  title %} Detail {{ setting.school }}  {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %} {{ setting.description }} {% endblock %}

{% block body %}
<link rel ='shortcut icon' type="image/icon" href = '{{setting.icon.url}}' />
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}


{% block  content %}
 <div class="content">
     <div class="content_resize">
    <div class="mainbar">
        {{ content.detail|safe }}
          </div>

            {% include 'sidebar.html' %}
          <div class="clr"></div>
    </div>
  </div>

{% endblock %}

home/templates/fag.html
{% extends "homebase.html" %}

{% block  title %} Sıkça Sorulan Sorular  {% endblock %}
{% block  keywords %} {{ categorydata.keywords }} {% endblock %}
{% block  description %} {{ categorydata.description }} {% endblock %}

{% block body %}
<link rel='shortcut icon' type="image/icon" href='{{setting.icon.url}}'/>


<!-- <script>
 $( function() {
   $( "#accordion" ).accordion();
 } );
 </script>--->

{% endblock %}


{% block  slider %}
{% include 'slider.html' %}
{% endblock %}


{% block  content %}
<div class="content">
    <div class="content_resize">
        <div class="mainbar">
            <strong>Sıkça Sorulan Sorular</strong>
            <div id="accordion">
                 {% for rs in faq %}
                <div class="card">
                    <div class="card-header" id="headingOne">
                        <h5 class="mb-0">
                            <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne"
                                    aria-expanded="true" aria-controls="collapseOne">
                                {{ rs.question }}
                            </button>
                        </h5>
                    </div>

                    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
                        <div class="card-body">
                           {{ rs.answer }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>


        </div>
    </div>

    {% endblock %}
</div>

home/templates/homebase.html
<!DOCTYPE html>
<html lang="en">
<head>
<!--    <meta charset="UTF-8">-->
    <title>{% block title %} Anasayfa {% endblock %} </title>
    <meta name="keywords" content="{% block keywords %} anasayfa anahtar keimeler {% endblock %}">
    <meta name="description" content="{% block description %} anasayfa anahtar keimeler {% endblock %}">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    {% load static %}

    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/coin-slider.css' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"> </script>
    <!-- jQuery UI !-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>



    {% block head %} {% endblock %}

</head>
{% include 'header.html' %}
<!--    {% block  sidebar %}  {% endblock %}
    {% block  slider %}  {% endblock %}-->
{% block content %} {% endblock %}
{% block body %} {% endblock %}
{% include 'footer.html' %}
{% block footer %} {% endblock %}


<body>

</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/cufon-yui.js' %}"></script>
<script type="text/javascript" src="{% static 'js/droid_sans_400-droid_sans_700.font.js' %}"></script>
<script type="text/javascript" src="{% static 'js/script.js '%}"></script>

<!--<script type="text/javascript" src="{% static 'js/jquery-1.4.2.min.js' %}"></script>-->
<script type="text/javascript" src="{% static 'js/coin-slider.min.js' %}"></script>
</html>

home/templates/slider.html
{% load static %}

<div class="clr"></div>
<div class="slider">
    <div id="coin-slider">
        {% for com in sliderdata%}
        <a href="/announcement/{{ com.id }}/{{ com.slug }}"><img src="{{ com.image.url }}" width="960" height="335" alt="" /> </a>
        {% endfor %}
    </div>
    <div class="clr"></div>
</div>
<div class="clr"></div>