home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index,  name='index')
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

project/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('user/', include('user.urls')),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('references/', views.references, name='references'),
    path('contactus/', views.contactus, name='contactus'),
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('announcement/', include('announcement.urls')),
    path('category/<int:id>/<slug:slug>/', views.category_products, name ='category_products'),
    path('announcement/<int:id>/<slug:slug>/', views.announcement_detail, name='announcement_detail'),
    path('search/', views.announcement_search, name='announcement_search'),
    path('search_auto/', views.announcement_search_auto, name='announcement_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('join/', views.join_view, name='join_view'),
    path('faq/', views.faq, name='faq'),
    path('menu/<int:id>', views.menu, name='menu'),
    path('menu/<int:id>/<slug:slug>', views.content_detail, name='content_detail'),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    #path('comments/', views.comments, name='comments'),
    # path('contents/', views.contents, name='contents'),
    # path('contentedit/<int:id>', views.contentedit, name='contentedit'),



]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

user/urls.py
from django.http import HttpResponse
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index,  name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),
    path('contentedit/<int:id>', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),
    # ex: /polls/5/
    # path('<int:question_id>/', views.detail, name='detail'),

]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import  ModelForm,TextInput, Textarea
from django.utils.safestring import mark_safe


class Settings(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    school = models.CharField(max_length=50)
    address = models.CharField(blank=True, max_length=100)
    phone = models.CharField(blank=True,max_length=15)
    fax = models.CharField(blank=True,max_length=15)
    email = models.CharField(blank=True,max_length=255)
    smtserver =models.CharField(blank=True,max_length=20)
    smtemail =models.CharField(blank=True,max_length=20)
    smtpassword = models.CharField(blank=True,max_length=10)
    smtpport = models.CharField(blank=True,max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook =models.CharField(blank=True,max_length=50)
    instagram =models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True,max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references =  RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    # create_at = models.DataTimeField(auto_now_add=True)
    # update_at = models.DataTimeFiled(auto_now_add=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),

    )
    name = models.CharField(blank = True, max_length=20)
    email= models.CharField(blank = True,max_length=50)
    subject = models.CharField(blank = True,max_length=50)
    message = models.CharField(blank = True,max_length=255)
    status = models.CharField (max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank = True,max_length=20)
    note = models.CharField(blank = True,max_length=100)
    # create_at = models.DataTimeField(auto_now_add=True)
    # update_at = models.DataTimeFiled(auto_now_add=True)

    def __str__(self):
        return self.name


class ContactFormu(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
             'name': TextInput(attrs={'class' : 'input', 'placeholder' : 'Name & Surname'}),
             'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
             'email' : TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
             'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message', 'rows':'5'}),
        }




class UserProfile(models.Model):
    user =models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.CharField(blank =True,max_length=20)
    adress = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image =models.ImageField(blank=True, upload_to='images/users/')


    def __str__(self):
        return self.user.username

    def user_name(self):
        return  self.user.first_name + ' ' + self.user.last_name + ' ' + '[' + self.user.username + ']'

    def image_tag(self):
        return mark_safe('<img src="{}" height ="50/>'.format(self.image.url))

    image_tag.short_description = 'Image'



class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'adress', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır'),

    )
    ordernumber =models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField(max_length=255)
    status = models.CharField(max_length=10, choices=STATUS)
    #created_at
    #updated_at

    def __str__(self):
        return self.question

user/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import EmailInput, TextInput, FileInput, Select

from home.models import UserProfile


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields =('username','email','first_name', 'last_name')
        widgets = {
         'username' : TextInput(attrs={'class':'input','placeholder':'username'}),
         'email': EmailInput(attrs={'class':'input','placeholder':'email'}),
         'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'first_name'}),
         'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),

       }


CITY = [
    ('Istanbul','Istanbul'),
    ('Ankara','Ankara'),
    ('Izmir', 'Izmir'),
]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'adress', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'adress': EmailInput(attrs={'class': 'input', 'placeholder': 'adress'}),
            'city': Select(attrs={'class': 'input','placeholder': 'city'}, choices=CITY),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),

        }

user/templates/change_password.html
{% extends "homebase.html" %}

{% block  title %} {{ profile.user_name }}  {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type="image/icon" href='{{setting.icon.url}}'/>
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}

{% block  body %}


<div class="content">
    <div class="content_resize">
        <div class="sidebar">
            {% include "user_panel.html" %}

        </div>
        <div class="mainbar" style="float:left;width:690">

            <div class="article">
                <h2><span>Change Password </span></h2>

                <div>
                    {% if messages %}
                    {% for message in messages %}
                    <div style="color :green; font-size:medium">
                        {{ messages | safe }}

                    </div>

                    {% endfor %}
                    {% endif %}
                </div>


                <form action="" method="post">
                    {% csrf_token %}
                    {% for field in form %}

                    {{ field.label_tag }} </br>
                    {{ field }}</br>
                    {% if field.help_text %}
                    <small style="color: grey"> {{ field.help_text }}</small>
                    {% endif %}
                    {% for error in fields.errors %}
                    <p style="color:grey"> {{ error }} </p>
                    {% endfor %}


                    {% endfor %}
                    <button type="submit">Save Changes</button>


                </form>


            </div>


        </div>
        <div class="clr"></div>
    </div>
</div>

{% endblock %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Content Gallery</title>
</head>
<body>
<h2>{{announcement.title}}</h2>
<hr>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">{{ message|safe }}</div>
    {% endfor %}
{% endif %}

<form method="POST" ENCTYPE="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="announcement_id" id="id_announcement_id" value=" {{ announcement.id }} ">
    <label for="id_title">Title</label>
    <input type="text" name="title" class="input" placeholder="title" maxlength="50" id="id_title">
    <label for="id_image">Title</label>
    <input type="file" name="image" class="input" placeholder="image" accept="image/*" id="id_image">
    <button class="primary-btn" type="submit">Upload Image</button>
</form>

<hr>
<h4>Yüklenen Resimler</h4>
{% for rs in images %}
    <img src="{{ rs.image.url }}" height="200">
{% endfor %}
</body>
</html>

user/templates/user_addcontent.html
{% extends "homebase.html" %}

{% block  title %} {{ profile.user_name }}  {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel ='shortcut icon' type="image/icon" href = '{{setting.icon.url}}' />
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}

{% block  body %}




<div class="content">
    <div class="content_resize" style="width:1300px">
           <div class="sidebar">
            {% include "user_panel.html" %}

        </div>
        <div class="mainbar" style="float:left;width:690">


        <div class="article">
            <h2><span>Add Content </span></h2>
              {% load static %}

              <form action="" method="POST" >
                      {% csrf_token %}
                       <div class="container">
                 {{ form.media }}
                 {{ form.as_p}}
                       </div>
                   <div>
                      <button type="submit">Save</button>
                   </div>
                </form>



        </div>

        </div>

          <div class="clr"></div>
    </div>
  </div>

{% endblock %}

user/templates/user_comments.html
{% extends "homebase.html" %}

{% block  title %} {{ profile.user_name }}  {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type="image/icon" href='{{setting.icon.url}}'/>
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}

{% block  body %}


<div class="content">
    <div class="content_resize">
        <div class="sidebar">
            {% include "user_panel.html" %}

        </div>
        <div class="mainbar" style="float:left;width:690">


            <div class="article">
                <h2><span>User Comments </span></h2>
<!--                <tr>
                    <th class="text-left">
                        <a href="/user/update" class=primary-btn>Update</a>
                        <a href="/user/password" class=primary-btn>Change Password</a>
                    </th>
                </tr>-->
                <table cellpadding="20" width="80">
                    <tr>
                        <th class="text-left"> Announcement</th>
                        <th class="text-left"> Rate</th>
                        <th class="text-left"> Subject</th>
                        <th class="text-left"> Comment</th>
                        <th class="text-left"> Status</th>
                        <th class="text-left"> Detail</th>
                    </tr>

                    {% for rs in comments %}
                    <tr>
                        <td class="text-left">
                        <a href="/announcement/ {{ rs.announcement_id }} /{{ rs.announcement.slug }}">{{rs.announcement}}</a>
                        </td>
                        <td class="text-left"> {{ rs.rate }}</td>
                        <td class="text-left"> {{ rs.subject }}</td>
                        <td class="text-left"> {{ rs.comment }}</td>
                        <td class="text-left"> {{ rs.status }}</td>
                        <td class="text-left">
                               <a href="/user/deletecomment/{{ rs.id }}" type="button" onclick="return confirm('Are you Sure')" class="btn btn-danger">Delete
                            </a>
<!--                            <a class=" primary-btn" href="/user/deletecomment/{{ rs.id }}"-->
<!--                                                 onclick="return confirm('Are you Sure')">Delete </a>-->
                        </td>
                    </tr>
                    {% endfor %}


                </table>
            </div>
        </div>
        <div class="clr"></div>
    </div>
</div>

{% endblock %}

user/templates/user_content.html
{% extends "homebase.html" %}

{% block  title %} {{ profile.user_name }}  {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type="image/icon" href='{{setting.icon.url}}'/>
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}

{% block  body %}


<div class="content">
    <div class="content_resize">
        <div class="sidebar">
            {% include "user_panel.html" %}

        </div>
        <div class="mainbar" style="float:left;width:690">

            <div class="article">
                <h2><span>My Content</span></h2>
                <!--  <tr>-->
                <th class="text-left">
                    <a href="/user/addcontent" type="button" class="btn btn-warning">Add Content</a>

                    <!--                    <a href="/user/addcontent" class=primary-btn>add content</a>-->

                </th>
                </tr>
                <table cellpadding="10" width="80">
                    <tr>
                        <th class="text-left"> Image</th>
                        <th class="text-left"> Title</th>
                        <th class="text-left"> Type</th>
                        <th class="text-left"> Menu</th>
                        <th class="text-left"> Gallery</th>
                        <th class="text-left"> Status</th>
                        <th class="text-left"> Detail</th>
                    </tr>

                    {% for rs in contents %}
                    <tr>
                       <!-- <td class="text-left">
                            &nbsp; <a href="/content/{{ rs.id }}/{{ rs.slug }}"></a></td>-->
                        <td class="text-left"><img src="{{ rs.image.url }}" width="50" height="50"> </a></td>

                        <td class="text-left"> {{ rs.title }}</td>
                        <td class="text-left"> {{ rs.type }}</td>
                        <td class="text-left"> {{ rs.menu.title }}</td>
                        <td class="text-left"> <a href="javascript:;" onclick="window.open('/user/contentaddimage/{{ rs.id }}','gallery','height=600,width=800,top=50,left=150')">Gallery</a></td>
                        <td class="text-left"> {{ rs.status }}</td>
                        <td class="text-left">
                            <a href="/user/contentedit/{{ rs.id }}" type="button" class="btn btn-warning">Edit
                            </a>
                            <!--                            <a href="/user/contentedit/{{ rs.id }}">Edit</a>-->
                        </td>
                        <td class="text-left">
                            <a href="/user/contentdelete/{{ rs.id }}" type="button" onclick="return confirm('Are you Sure')" class="btn btn-danger">Delete
                            </a>

                            <!--                            <a class=" primary-btn" href="/user/contentdelete/{{ rs.id }}"-->
                            <!--                               onclick="return confirm('Are you Sure')">Delete </a>-->
                        </td>
                    </tr>
                    {% endfor %}


                </table>
            </div>
        </div>

        <div class="clr"></div>
    </div>
</div>

{% endblock %}

user/templates/user_panel.html
<div class="gadget">
          <h2 class="star"><span>User</span> Menu</h2>
          <div class="clr"></div>
          <ul class="sb_menu">
            <li><a href="/user">My Profile</a></li>
            <li><a href="/user/comments">My Comments</a></li>
              <li><a href="/user/contents">My Contents</a></li>
            <li><a href="/logout">Logout</a></li>
          </ul>
</div>

user/templates/user_profile.html
{% extends "homebase.html" %}

{% block  title %} {{ profile.user_name }}  {% endblock %}
{% block  keywords %} {{ setting.keywords }} {% endblock %}
{% block  description %} {{ setting.description }} {% endblock %}

{% block head %}
<link rel='shortcut icon' type="image/icon" href='{{setting.icon.url}}'/>
{% endblock %}

{% block  slider %}
{% include 'slider.html' %}
{% endblock %}

{% block  body %}


<div class="content">
    <div class="content_resize">
        <div class="sidebar">
            {% include "user_panel.html" %}

        </div>
        <div class="mainbar" style="float:left;width:690">


            <div class="article">
                <h2><span>User Information </span></h2>
                <tr>
                    <th class="text-left">
                        <a href="/user/update" type="button" class="btn btn-warning">Update</a>
                        <a href="/user/password" type="button" class="btn btn-primary">Change Password</a>
<!--                        <a href="/user/update" class=primary-btn>Update</a>-->
<!--                        <a href="/user/password" class=primary-btn>Change Password</a>-->
                    </th>
                </tr>
                <table cellpadding="20" width="80">
                    <tr>
                        <th>Images</th>
                        <td><img src="{{ profile.image.url }}" height="70" weight="70"></a></td>
                    </tr>
                    <th> Name Surname</th>
                    <td> {{ profile.user_name }}</td>
                    <tr>
                    <tr>
                        <th>Email</th>
                        <td> {{ profile.user.email }}</td>
                    </tr>
                    <tr>
                        <th>Phone</th>
                        <td> {{ profile.phone }}</td>
                    </tr>
                    <tr>
                        <th>Adress</th>
                        <td> {{ profile.adress }}</td>
                    </tr>
                    <tr>
                        <th>City</th>
                        <td> {{ profile.city }}</td>
                    </tr>
                    <tr>
                        <th>Country</th>
                        <td> {{ profile.country }}</td>
                    </tr>

                </table>


            </div>

        </div>

        <div class="clr"></div>
    </div>
</div>

{% endblock %}